// Frontend Development/Hands_on_6/Task 3/Components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header className="header">
      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link>{" "}
        <Link to="/courses">Courses</Link>{" "}
        <Link to="/profile">Profile</Link>
      </nav>

      <h3>Enrolled Courses: {enrolledCourses.length}</h3>
    </header>
  );
}

export default Header;

// Frontend Development/Hands_on_8/Task 3/Components/Header.vue
<template>
  <header class="header">

    <h1>Student Portal</h1>

    <h3>
      Enrolled Courses :
      {{ store.enrolledCourses.length }}
    </h3>

  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background: #42b883;
  color: white;
  text-align: center;
  padding: 18px;
  border-radius: 8px;
  margin-bottom: 20px;
}
</style>
